allow a way to test that custom exit code on panic works
and that by using that custom code, the drop() aka destructors still get
executed, unlike an exit()

diff --git a/rust/05_sandbox/diff/both_as_diff_patch_replacements/g b/rust/05_sandbox/diff/both_as_diff_patch_replacements/g
--- a/rust/05_sandbox/diff/both_as_diff_patch_replacements/g
+++ b/rust/05_sandbox/diff/both_as_diff_patch_replacements/g
@@ -11,6 +11,18 @@ set +e
 exe="$(realpath -- ./target/debug/both_as_diff_patch_replacements)"
 ln -frs "$exe" ./diff
 ln -frs "$exe" ./patch
+ln -frs "$exe" ./test_drops_and_exit_code_on_panic
+./test_drops_and_exit_code_on_panic ; ec="$?"
+if test "$ec" != "82"; then
+  tput setaf 1 >&2
+  echo "Failed, exit code 82, not '$ec', was expected." >&2
+  tput sgr0 >&2
+  exit "$ec"
+else
+  tput setaf 2 >&2
+  echo "That worked, exit code '$ec', continuing..." >&2
+  tput sgr0 >&2
+fi
 diff="$(realpath --no-symlinks -- ./diff)"
 patch="$(realpath --no-symlinks -- ./patch)"
 pushd "../diff"
