improvements to diff/patch projects
and simplified poc patch

diff --git a/rust/05_sandbox/diff/patch/g b/rust/05_sandbox/diff/patch/g
--- a/rust/05_sandbox/diff/patch/g
+++ b/rust/05_sandbox/diff/patch/g
@@ -2,23 +2,33 @@
 
 set -e
 export RUST_BACKTRACE=1
-cargo clean
+#cargo clean
 cargo build
 #set -vx
 set +e
 cargo run workspace.rs.original le.patch workspace.rs.FRESHLY_PATCHED
 cargo run workspace.rs.FRESHLY_PATCHED le.patch workspace.rs.FRESHLY_PATCHED_AGAIN; ec="$?"
 if test "$ec" == 0; then
-  echo "That's a fail, it shouldn't have applied again!" >&2
+  echo "That's a fail, it shouldn't have applied again! The patch itself is ambiguous!" >&2
   cargo run workspace.rs.FRESHLY_PATCHED_AGAIN le.patch workspace.rs.FRESHLY_PATCHED_AGAIN2; ec="$?"
   if test "$ec" == 0; then
-    echo "That's a fail, it shouldn't have applied again!" >&2
+    echo "That's a fail, it shouldn't have applied again! The patch itself is ambiguous!" >&2
+    echo "Now let's try again but this time with unambiguous apply!" >&2
   else
     echo "That's correct! Patch failed to apply again in a wrong place!" >&2
   fi
+
   #cargo run workspace.rs.FRESHLY_PATCHED_AGAIN2 le.patch workspace.rs.FRESHLY_PATCHED_AGAIN3
   #^ that one finally fails!
 else
   echo "That's correct! Patch failed to apply again in a wrong place!" >&2
+  echo "Now let's try again but this time with an ambiguous patch and an unambiguous apply!" >&2
 fi
 
+cargo run workspace.rs.original bad.patch workspace.rs.FRESHLY_PATCHED true ; ec="$?"
+if test "$ec" != 0; then
+  echo "That's correct, applying an ambiguous patch unambiguously, failed as it should!" >&2
+else
+  echo "Incorrect, unambiguously applying the ambiguous patch should not have succeeded!" >&2
+  exit "$ec"
+fi
