make ./go work even when clippy doesn't
and use map_err when the futures return different Result types! ie. just
to show how it's done, src: end of this page https://rust-lang.github.io/async-book/06_multiple_futures/02_join.html#try_join

diff --git a/helper_scripts/go b/helper_scripts/go
--- a/helper_scripts/go
+++ b/helper_scripts/go
@@ -8,8 +8,13 @@ if test -x ./prereq; then
   ./prereq
 fi
 if test "$1" != "noclippy"; then
-  set -e
-  time cargo clippy "$@"
+  if clippy-driver; then
+    set -e
+    time cargo clippy "$@"
+  else
+    echo "Skipping clippy because clippy-driver failed to load .so (guessing)" >&2
+    #/home/user/.cargo/bin/clippy-driver: error while loading shared libraries: librustc_driver-62440e4dfa357b84.so: cannot open shared object file: No such file or directory
+  fi
 else
   shift 1
 fi
