kinda prepared 'diff' wrapper, delegating work to 'patch'

diff --git a/patch/hunk_applied_to_wrong_place/diff b/patch/hunk_applied_to_wrong_place/diff
--- a/patch/hunk_applied_to_wrong_place/diff
+++ b/patch/hunk_applied_to_wrong_place/diff
@@ -59,10 +59,11 @@ elif test "$unambiguous" == "1"; then
   echo "$diffcalledmsg" >&1
   stdout_file="$(mktemp)"
   stderr_file="$(mktemp)"
+  stderr_file_anew="$(mktemp)"
 
-  "${diff}" --show-filenames-on-stderr "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
+  "${diff}" --show-filenames-on-stderr --show-unified-arg-value "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
   #"${diff}" "${remaining_args[@]}"
-  cat "$stdout_file" >&1
+  #cat "$stdout_file" >&1 #not yet! we don't know if it's good, so later!
   #cat "$stderr_file" >&2 #we output this later in the 'while' below
 
   #Note that because --label LABEL is a thing, each filename in the output diff can be overwritten with LABEL, so can't extract it from there! That's why trying to use the filenames from the args, well the filenames that 'diff' sees are filenames and aren't set to be treated as binary!
@@ -80,6 +81,8 @@ elif test "$unambiguous" == "1"; then
   # Variables to store filenames aka the file arguments given to the 'diff' command
   file1=""
   file2=""
+  unified_arg=""
+  MAX_UNIFIED_VALUE=15
 
   # Read the stderr input file line by line, and only output the lines that aren't part of the --show-filenames-on-stderr output
   while IFS= read -r line; do
@@ -87,13 +90,28 @@ elif test "$unambiguous" == "1"; then
     # Check if the line matches the fixed string
     if [[ "$line" == "diff: Comparing non-binary files:" ]]; then
       # Read the next two lines to get the filenames
-      read -r file1
-      read -r file2
+      #-r	do not allow backslashes to escape any characters
+      #-t timeout	time out and return failure if a complete line of
+      #		input is not read within TIMEOUT seconds.  The value of the
+      #		TMOUT variable is the default timeout.  TIMEOUT may be a
+      #		fractional number.  If TIMEOUT is 0, read returns
+      #		immediately, without trying to read any data, returning
+      #		success only if input is available on the specified
+      #		file descriptor.  The exit status is greater than 128
+      #		if the timeout is exceeded
+      read -r -t 1 file1
+      read -r -t 1 file2
+    elif [[ "$line" == "diff: the value of the --unified arg is:" ]]; then
+      #^ that shows only when --show-unified-arg-value is used! which means ur 'diff' is patched!
+      read -r -t 1 unified_arg
     else
-      # Print the line to stderr
-      echo "$line" >&2
+      #don't print the saved stderr out now, save it for later, but without including the above!
+      echo "$line" > "$stderr_file_anew"
     fi
   done < "$stderr_file"
+  #we filtered out the stuff
+  rm -v -- "$stderr_file" >&2
+  stderr_file="$stderr_file_anew"
 
   if test -z "$file1" -o ! -e "$file1"; then
     echo "First file '$file1' is empty or not a file" >&2
@@ -103,9 +121,17 @@ elif test "$unambiguous" == "1"; then
     echo "Second file '$file2' is empty or not a file" >&2
     exit 12
   fi
-  # Print the filenames to stdout for confirmation
-  echo "file1: $file1" >&2
-  echo "file2: $file2" >&2
+  if test -z "$unified_arg"; then
+    echo "The detected --unified=NUM (or -u NUM) arg is empty probably because it wasn't used, to make this work you've to specify $AMBIGUOUS_ARG which won't check if the same hunk can be applied more than once in the same file. Because $THE_UNAMBIGUOUS_ARG only works with -u arg and you apparently don't want to use it at the moment." >&2
+    exit 14
+  fi
+  if ! [[ $unified_arg =~ ^[0-9]+$ ]]; then
+    echo "The detected --unified=NUM (or -u NUM) arg value of '$unified_arg' is not a number which is unexpectedly odd!" >&2
+    exit 15
+  fi
+#  # Print the filenames to stdout for confirmation
+#  echo "file1: $file1" >&2
+#  echo "file2: $file2" >&2
 
   how_many_files_patched="$(grep -c '^+++' -- "$stdout_file")"
   if test "$how_many_files_patched" -gt "1"; then
@@ -115,6 +141,56 @@ elif test "$unambiguous" == "1"; then
 
   #so now make a temp copy of file1, try to apply the resulting 'diff' patch twice and make sure the second time fails fully, no succees hunks! if fails fully then it's unabiguous, else it means the same hunk could be applied in two or more different places!
   #hmm, this isn't actually fullproof, hmm... maybe doing this for each hunk independently would be best?! because i can imagine having 2 hunks but each could be swapped because the spots yield are same-contents diff except the line numbers. Plus also, if the original file changes like it adds another same-contents spot, then 'diff' won't know, but 'patch' itself will when i modify it soon so it won't apply any hunk that can be applied more than once if u tried.
+
+  pec=1 #to get into the 'while'
+  set -e
+  tmpsubdir="$(mktemp -d)" #FIXME: delete this when done!
+  set +e
+  file1basename="$(basename "$file1")"
+  while test "$pec" != 0; do
+    #deref symlinks
+    cp --dereference -- "$file1" "$tmpsubdir"
+    set -e
+    pushd "$tmpsubdir"
+    set +e
+    #we already made sure there's only one file inside the patch, we ignore its name inside the patch tho! we tell 'patch' which name it has on cmdline!
+    #       patch [options] [originalfile [patchfile]]
+    patch "$THE_UNAMBIGUOUS_ARG" -- "$file1basename" "$stdout_file"; pec="$?"
+    set -e
+    popd
+    set +e
+    if test "$pec" != "0"; then
+       unified_arg_next=$((unified_arg + 1))
+      echo "!! The generated diff '$stdout_file' failed to apply with $THE_UNAMBIGUOUS_ARG and --unified=$unified_arg with exit code '$pec', next retrying with --unified=$unified_arg_next" >&2
+      # Increment the numeric value by 1
+      unified_arg=$(( unified_arg_next ))
+      if test "$unified_arg" -gt "$MAX_UNIFIED_VALUE"; then
+        echo "The value of --unified=$unified_arg to try next is higher than MAX allowed to try '$MAX_UNIFIED_VALUE', ergo stopping with failure: the generated diff cannot be unambiguously applied, ie. a hunk can be accidentally placed in a different spot by 'patch' and you can only hope it's a compile error that detects that, else it's gonna be different runtime behaviour from wtw you patched!" >&2
+        cat "$stdout_file" >&1
+        cat "$stderr_file" >&2 #NVMactually this got already printed, well, kind of, let's fix that so it's not already!
+        echo "!! You may inspect stdout and stderr as tmp files $stdout_file respectively $stderr_file, but they got printed above." >&2
+        ec="98"
+        break
+      fi
+      # TODO: if wanting to be too pedantic prepend --show-unified-arg-value to diff cmd below and check if indeed the value that we passed was used!
+      #the last -u NUM used is in effect! so wtw user specified before even if it's inside $remaining_args it doesn't matter as long as our override comes last!
+      #retry with higher(+1) --unified=NUM
+      "${diff}" "${remaining_args[@]}" "--unified=$unified_arg" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
+      if test "$ec" != "0"; then
+        cat "$stdout_file" >&1
+        cat "$stderr_file" >&2
+        echo "!! You may inspect stdout and stderr as tmp files $stdout_file respectively $stderr_file, but they got printed above." >&2
+        break #out of the 'while', ec is already set so we'll exit code properly!
+      fi
+      #else 'diff' succeeded ok, semidoneFIXME: to avoid infinite loop, find out if the generated patch is same (eg. maybe it's too small and any -u NUM value has no effect on the generated output patch!) OR don't -u NUM for a NUM higher than MAX
+    else
+      #patch ok, print it out
+      cat "$stdout_file" >&1
+      #and wtw stderr was
+      cat "$stderr_file" >&2
+    fi
+  done
+
 
   rm -v -- "$stdout_file" "$stderr_file" >&2
   #echo "$stdout_file" "$stderr_file" >&2
