renames

diff --git a/patch/hunk_applied_to_wrong_place/diff b/patch/hunk_applied_to_wrong_place/diff
--- a/patch/hunk_applied_to_wrong_place/diff
+++ b/patch/hunk_applied_to_wrong_place/diff
@@ -61,7 +61,7 @@ elif test "$unambiguous" == "1"; then
   stderr_file="$(mktemp)"
   stderr_file_anew="$(mktemp)"
 
-  "${diff}" --show-filenames-on-stderr --show-unified-arg-value "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
+  "${diff}" --show-filenames-on-stderr --show-context-length-value "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
   #"Exit status is 0 if inputs are the same, 1 if different, 2 if trouble." - man 1 diff
   if test "$ec" == "0"; then
     #there's no differences between the files!
@@ -90,8 +90,8 @@ elif test "$unambiguous" == "1"; then
   # Variables to store filenames aka the file arguments given to the 'diff' command
   file1=""
   file2=""
-  unified_arg=""
-  MAX_UNIFIED_VALUE=15
+  context_length=""
+  MAX_CONTEXT_LINES=15
 
   # Read the stderr input file line by line, and only output the lines that aren't part of the --show-filenames-on-stderr output
   while IFS= read -r line; do
@@ -110,9 +110,9 @@ elif test "$unambiguous" == "1"; then
       #		if the timeout is exceeded
       read -r -t 1 file1
       read -r -t 1 file2
-    elif [[ "$line" == "diff: the value of the --unified arg is:" ]]; then
-      #^ that shows only when --show-unified-arg-value is used! which means ur 'diff' is patched!
-      read -r -t 1 unified_arg
+    elif [[ "$line" == "diff: the value of the context length aka lines is:" ]]; then
+      #^ that shows only when --show-context-length-value is used! which means ur 'diff' is patched!
+      read -r -t 1 context_length
     else
       #don't print the saved stderr out now, save it for later, but without including the above!
       echo "$line" > "$stderr_file_anew"
@@ -130,12 +130,12 @@ elif test "$unambiguous" == "1"; then
     echo "Second file '$file2' is empty or not a file" >&2
     exit 12
   fi
-  if test -z "$unified_arg"; then
-    echo "The detected --unified=NUM (or -U NUM) arg is empty probably because it wasn't used, to make this work you've to specify $AMBIGUOUS_ARG which won't check if the same hunk can be applied more than once in the same file. Because $THE_UNAMBIGUOUS_ARG only works with -u arg and you apparently don't want to use it at the moment." >&2
+  if test -z "$context_length"; then
+    echo "The detected context length(lines) is empty which is very odd and points to coding inconsistencies on my part" >&2
     exit 14
   fi
-  if ! [[ $unified_arg =~ ^[0-9]+$ ]]; then
-    echo "The detected --unified=NUM (or -U NUM) arg value of '$unified_arg' is not a number which is unexpectedly odd!" >&2
+  if ! [[ $context_length =~ ^[0-9]+$ ]]; then
+    echo "The detected context length(lines) is '$context_length' but it's not a number which is unexpectedly odd!" >&2
     exit 15
   fi
 #  # Print the filenames to stdout for confirmation
@@ -170,25 +170,25 @@ elif test "$unambiguous" == "1"; then
     set +e
     #"patch’s exit status is 0 if all hunks are applied successfully, 1 if some hunks cannot be applied or there  were merge  conflicts,  and 2 if there is more serious trouble." - man 1 patch
     if test "$pec" != "0"; then
-       unified_arg_next=$((unified_arg + 1))
-      echo "!! The generated diff '$stdout_file' failed to apply with $THE_UNAMBIGUOUS_ARG and --unified=$unified_arg with exit code '$pec', next retrying patch generation with +1 context lines ie. --override-context-lines=$unified_arg_next" >&2
+       context_length_next=$((context_length + 1))
+       echo "!! The generated diff '$stdout_file' (having been generated by a diff with '$context_length' lines of context) failed to apply with patch command using $THE_UNAMBIGUOUS_ARG arg, exit code '$pec', next retrying patch generation via diff command with +1 context lines ie. --override-context-lines=$context_length_next" >&2
       # Increment the numeric value by 1
-      unified_arg=$(( unified_arg_next ))
-      if test "$unified_arg" -gt "$MAX_UNIFIED_VALUE"; then
-        echo "The value of --override-context-lines=$unified_arg to try next is higher than MAX allowed to try '$MAX_UNIFIED_VALUE', ergo stopping with failure: the generated diff cannot be unambiguously applied, ie. a hunk can be accidentally placed in a different spot by 'patch' and you can only hope it's a compile error that detects that, else it's gonna be different runtime behaviour from wtw you patched!" >&2
+      context_length=$(( context_length_next ))
+      if test "$context_length" -gt "$MAX_CONTEXT_LINES"; then
+        echo "The value of --override-context-lines=$context_length to try next is higher than MAX allowed to try '$MAX_CONTEXT_LINES', ergo stopping with failure: the generated diff cannot be unambiguously applied, ie. a hunk can be accidentally placed in a different spot by 'patch' and you can only hope it's a compile error that detects that, else it's gonna be different runtime behaviour from wtw you patched!" >&2
         cat "$stdout_file" >&1
         cat "$stderr_file" >&2 #NVMactually this got already printed, well, kind of, let's fix that so it's not already!
         echo "!! You may inspect stdout and stderr as tmp files $stdout_file respectively $stderr_file, but they got printed above." >&2
         ec="98"
         break
       fi
-      # TODO: if wanting to be too pedantic prepend --show-unified-arg-value to diff cmd below and check if indeed the value that we passed was used!
+      # TODO: if wanting to be too pedantic prepend --show-context-length-value to diff cmd below and check if indeed the value that we passed was used!
       #the last -U NUM used is in effect! so wtw user specified before even if it's inside $remaining_args it doesn't matter as long as our override comes last!
-      #retry with higher(+1) --unified=NUM
-      #doneFIXME: this won't work because the arg we add is after the files and more importantly after a possible '--' arg, which means end of option args! So we need an overrider arg! like --override-unified=NUM which ignores any subsequent ones, somehow! /usr/bin/diff: extra operand '--unified=4'
-      #"${diff}" "${remaining_args[@]}" "--unified=$unified_arg" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
+      #retry with higher(+1) context length(lines)
+      #doneFIXME: this won't work because the arg we add is after the files and more importantly after a possible '--' arg, which means end of option args! So we need an overrider arg! like --override-context-lines=NUM which ignores any subsequent ones, somehow! /usr/bin/diff: extra operand '--unified=4'
+      #"${diff}" "${remaining_args[@]}" "--unified=$context_length" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
       #--override-context-lines=NUM overrides any subsequent(or previous) setting attempts via -u, -c, -NUM, -U NUM, -C NUM, of context lines! ('diff' needs patch for this, obviously)
-      "${diff}" "--override-context-lines=$unified_arg" "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
+      "${diff}" "--override-context-lines=$context_length" "${remaining_args[@]}" 1> "$stdout_file" 2> "$stderr_file" ; ec="$?"
       #"Exit status is 0 if inputs are the same, 1 if different, 2 if trouble." - man 1 diff
       #TODO: print the args on stdout and exit code, so it's part of the patch too!
       if test "$ec" != "0" -a "$ec" != "1"; then
