WIP advance to 'patch'

diff --git a/patch/hunk_applied_to_wrong_place/patch b/patch/hunk_applied_to_wrong_place/patch
--- a/patch/hunk_applied_to_wrong_place/patch
+++ b/patch/hunk_applied_to_wrong_place/patch
@@ -2,16 +2,89 @@
 
 #XXX unconditionally use -F 0 aka no fuzz! because the default of 2 fuzz applied a cargo patch wrongly and yielded a compilation error! the code was in a different function!!
 #TODO: add the functionality from this patch: /home/user/build/1packages/4used/pacman/1pacman-git/applyallpatches_and_patch2_functions_implement.patch
-#patchexeabs="/usr/bin/patch"
-patchexeabs="/var/tmp/portage/sys-devel/patch-2.7.6-r5/work/patch-2.7.6/src/patch"
-if test ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5" -o ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5/work" -o ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5/work/patch-2.7.6"; then
-  sudo -- chmod a+x "/var/tmp/portage/sys-devel/patch-2.7.6-r5"{,/work,/work/patch-2.7.6}
+patchexeabs="/usr/bin/patch"
+#patchexeabs="/var/tmp/portage/sys-devel/patch-2.7.6-r5/work/patch-2.7.6/src/patch"
+#if test ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5" -o ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5/work" -o ! -x "/var/tmp/portage/sys-devel/patch-2.7.6-r5/work/patch-2.7.6"; then
+#  sudo -- chmod a+x "/var/tmp/portage/sys-devel/patch-2.7.6-r5"{,/work,/work/patch-2.7.6}
+#fi
+if test -z "$patchexeabs"; then
+  echo "empty \$patchexeabs" >&2
+  exit 99
 fi
-#"${patchexeabs}" --read-only=fail --verbose --debug=65535 --fuzz=0 "$@" #last working XXX#
-"${patchexeabs}" --read-only=fail --debug=0 --fuzz=0 "$@" #last working XXX#
-#command -p patch --read-only=fail --verbose --debug=0 --fuzz=0 "$@" #untested but should be same as before^
-#added 24 july 2020: --read-only=fail --verbose --debug=65535  #note: decided to not use --set-time OR --set-utc   at this time.
-#removed --debug=65535 on 26 july 2020
+AMBIGUOUS_ARG="--ambiguous"
+THE_UNAMBIGUOUS_ARG="--unambiguous"
+
+unambiguous=1
+#^ unambiguous by default, which means, don't allow same hunk to can be applied in more than 1 place in the same file!
+
+# Array to store the remaining arguments
+remaining_args=()
+at_saved=("$@")
+
+# Iterate over the arguments
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    "${AMBIGUOUS_ARG}")
+      unambiguous=0
+      #^ explicitly not checking if hunks can be applied to more than 1 place in the file.
+      shift
+      ;;
+    "${THE_UNAMBIGUOUS_ARG}")
+      unambiguous=1
+      #^ explicitly checking if hunks can be applied to more than 1 place in the file.
+      shift
+      ;;
+    *)
+      # Add argument to remaining_args array
+      remaining_args+=("$1")
+      shift
+      ;;
+  esac
+done
+
+#XXX "$@" is unusable after the above "shift"(s)
+
+if test "$unambiguous" == "0"; then
+  #"${patchexeabs}" --read-only=fail --verbose --debug=65535 --fuzz=0 "$@" #last working XXX#
+  "${patchexeabs}" --read-only=fail --debug=0 --fuzz=0 "${at_saved[@]}" #last working XXX#
+  #command -p patch --read-only=fail --verbose --debug=0 --fuzz=0 "$@" #untested but should be same as before^
+  #added 24 july 2020: --read-only=fail --verbose --debug=65535  #note: decided to not use --set-time OR --set-utc   at this time.
+  #removed --debug=65535 on 26 july 2020
+elif test "$unambiguous" == "1"; then
+  #XXX: expecting to have been called like this, and the file is in current dir:
+  #"${patch}" --special-call "$THE_UNAMBIGUOUS_ARG" -- "$file1basename" "$patch_file"; pec="$?"
+  if test "${remaining_args[0]}" != "--special-call" -o "${remaining_args[1]}" != "--"; then
+    echo "This call of 'patch' wrapper('$0') via $THE_UNAMBIGUOUS_ARG , can only handle calls via the 'diff' wrapper, but this was called with '${#at_saved[@]}' args '${at_saved[*]}'" >&2
+    exit 3
+  fi
+  file1basename="${remaining_args[2]}"
+  patch_file="${remaining_args[3]}"
+
+  how_many_files_patched="$(grep -c '^+++' -- "$patch_file")"
+  if test "$how_many_files_patched" -gt "1"; then
+    #worksTODO: unsure if $0 works here? wasn't $@ obliterated above?
+    #FIXME: obviously, needs to support this with --unambiguous too! but for now just wanna see how the hunks get processed for 1 patched file, without the extra complexity of handling more files.
+    echo "'patch' wrapper cmd('$0') has detected more than 1 file being patched, to support that pass arg $AMBIGUOUS_ARG which won't check if the same hunk can be applied more than once in the same file." >&2
+    exit 13
+  fi
+  if test ! -e "$file1basename"; then
+    echo "filename '$file1basename' wasn't found in pwd=$(pwd)" >&2
+    exit 5
+  fi
+  if test ! -e "$patch_file"; then
+    echo "patch file '$patch_file' wasn't found in pwd=$(pwd)" >&2
+    exit 6
+  fi
+  echo "patch wrapper found file1basename='$file1basename' and patch_file='$patch_file'" >&2
+  exit 4 #FIXME
+  #here we must test if each hunk of the patch applies successfully more than once, which means, it can apply to more than 1 unique spot in the file!
+  #worksanywayTODO: ensure somehow, that the hunk doesn't create another spot for itself to apply in? well, the patch will fail properly if it does.
+else
+  echo "Bad coding in '$0'" >&2
+  ec="100"
+fi
+
+exit "$ec"
 
 #TODO: 23 march 2022, I must detect dangling hunks, ie. hunks that are separated by anything other than comments (eg. new line(s)) because 'patch' will ignore them and treat them as comments, atually the whole file to patch is considered done at that point, and the next hunks if any are ignored as comments! silently!
 
